### PR TITLE
1.3.0 Changes

### PR DESCRIPTION
**Pull request by puddi**
Changes: 

* Updates the UI for default images, so that the placeholder doesn't render as a half-circle, and the entire image view is clickable.
* Updates the logic for small images. If an image is too small in either direction (vertical or horizontal), then we'll scale the image accordingly.

I think screenshots better explain this.

## Old

screen shot 2015-10-22 at 12 04 30 pm

screen shot 2015-10-22 at 12 11 12 pm

## New

screen shot 2015-10-22 at 12 04 35 pm

screen shot 2015-10-22 at 12 05 28 pm

@M-Porter

### CODE REVIEW

**Comment by M-Porter** [comment]
what does it look like when you test for portrait sized pictures?

**Comment by puddi** [comment]
Seems to look fine, outside the usual problems w/ upscales.

You know what would be super cool? Throwing it through a neural network to generate an upscaled version.

screen shot 2015-10-22 at 1 15 02 pm

**Comment by M-Porter** [comment]
the image doesnt seem to fill the full width or align veritcally to the top (flat edges).

**Comment by puddi** [comment]
that is... weird, because i tried reproducing and it looked fine

**Comment by M-Porter** [comment]
Ok cool. We'll just tack it up to the weebly image element being weird.

**Pull request merged**
